### ISSUE TITLE
建议后端增加proxy_protocol功能

### ISSUE THREAD

**Issue by asdyyx1** [Anankke/shadowsocks-mod#38]
当通过中转的时候面板显示的IP为中转IP或是127.0.0.1，建议增加proxy_protocol功能实现获取真实IP功能。
而且现在支持proxy_protocol的中转程序和后端都有不少，后端收费的Soga，免费的XrayR都是可以获取真实IP，不过XrayR没有SSR协议，希望官方后端增加这个功能。

https://www.haproxy.org/download/2.6/doc/proxy-protocol.txt
https://github.com/icgood/proxy-protocol

支持proxy_protocol的中转程序
 + haproxy
 + nginx
 + [zephyrchien/realm](https://github.com/zephyrchien/realm)

支持proxy_protocol的后端
 + XrayR
 + Soga

**Comment by Anankke** [comment]
本来就有，不过没写 doc，你试试看？

**Comment by asdyyx1** [comment]
> 本来就有，不过没写 doc，你试试看？

测试了一下确实支持，我看apiconfig.py没有相关开关以为没有，可以关闭这个issues
