### ISSUE TITLE
安装后无法登录

### ISSUE THREAD

**Issue by frankniubi** [Anankke/shadowsocks-mod#40]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel2.fingerprint' doesn't exist (SQL: insert into `fingerprint` (`user_id`, `fingerprint`, `created_at`) values (1, 28a7155bcf729685692951f579ea2d07, 1650907277))

用了新版 导入的也是新版的sql

**Comment by iamsaltedfish** [comment]
vendor/bin/phinx migrate
