### ISSUE TITLE
错误:不支持CPU架构

### ISSUE THREAD

**Issue by Yut-jing** [Anankke/shadowsocks-mod#41]
shadowsocks-mod server installation script for RHEL/Fedora
Author: M1Screw
Github: https://github.com/M1Screw/Airport-toolkit
Usage:
./ssr_node.sh install --> Install shadowsocks-mod server
./ssr_node.sh config --> Configure shadowsocks-mod server
./ssr_node.sh update --> Update shadowsocks-mod server
Detecting CPU Architecture...
Error: Unsupported CPU Architecture!
换了几个系统都一样报错，cpu是E5的V3系列，老的cpu型号都不支持吗？

**Comment by galaxychuck** [comment]
@ken136818346 32位系统或者ARM核心？

**Comment by galaxychuck** [comment]
@galaxychuck if [[ $cpu_arch != "x86_64" || $cpu_arch != "aarch64" ]]

**Comment by Yut-jing** [comment]
> @galaxychuck if [[ $cpu_arch != "x86_64" || $cpu_arch != "aarch64" ]]

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2630L v3 @ 1.80GHz
stepping	: 2
microcode	: 0x43
cpu MHz		: 1795.842
cache size	: 20480 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities
vmx flags	: vnmi invvpid ept_x_only ept_ad tsc_offset vtpr mtf ept vpid unrestricted_guest ple
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 3591.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 45 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2630L v3 @ 1.80GHz
stepping	: 2
microcode	: 0x43
cpu MHz		: 1795.842
cache size	: 20480 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities
vmx flags	: vnmi invvpid ept_x_only ept_ad tsc_offset vtpr mtf ept vpid unrestricted_guest ple
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 3591.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 45 bits physical, 48 bits virtual
power management:

**Comment by Yut-jing** [comment]
Linux fedora 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by galaxychuck** [comment]
@Yut-jing 把ssh脚本验证cpu那段删了试试

**Comment by ghost** [comment]
Fixed.
