### ISSUE TITLE
官方节点对接后端脚本错误，无法运行，报错，Unsupported OS version

### ISSUE THREAD

**Issue by ghost** [Anankke/shadowsocks-mod#42]
Environment 环境
CentOS Linux release 7.3.1611 (Core)
Ubuntu 18.04 LTS

按照下面教程给的，
https://wiki.sspanel.org/#/shadowsocks-mod-install-script
分别在CentOS Linux release 7.3.1611 (Core)，
Ubuntu 18.04 LTS 运行该脚本trojan_node.sh，ssr_node.sh都报错，提示不支持系统。

Detecting CPU Architecture...
Detecting OS...
Error: Unsupported OS!

Detecting CPU Architecture...
Detecting OS...
Error: Unsupported OS version!

**Comment by ShawLyon** [comment]
![image](https://user-images.githubusercontent.com/24935255/194735899-202047d7-488a-46a1-b1ad-c91758058b1b.png)
必须centos8或9,7不行
